USE saendwave;
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Amp Designer', '2.50', 'Amp Deisgner simula il suono di pù di 20 famosi amplificatori per chitarra e speaker collegati. Ognuno preconfigurato come combinazione di testata, cabinet e equalizzatore. Processa il segnale direttamente riproducendo il suono attraverso questa combinazione. Testata, cabinet ed equalizzatore possono essere combinati in numerosi modi per alterare il suono. Inoltre, vengono simulati microfoni virtuali che catturano il suono direttamente dal cabinet sui quali si può scegliere tipo e posizione rispetto agli speaker.', 'img/prodotti/Amp_Designer.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('AU Distortion', '1.50', 'L\'AU Distortion sporca il suono nel modo giusto. Dal sottile calore armonico alla distruzione totale del segnale, applichiamo una saturazione su misura per dare aggressività, presenza e \"grit\" a linee di basso, batterie o sintetizzatori altrimenti troppo puliti e spenti', 'img/prodotti/AU_Distortion.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Bass Amp Designer', '2.50', 'Il trattamento definitivo per la tua traccia di basso, Uniamo la pulizia di una Direct Box con la spinta e la profondità di un vero amplificatore microfonato. Garantisce basse frequenze solide, compatte e definite che \"bucano\" l\'impianto senza impastare il brano.', 'img/prodotti/Bass_Amp_Designer.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Chroma Verb', '1.50', 'Aggiungi spazio, tridimensionalità e respiro alla tua traccia. Dall\'intimità di una piccola stanza di registrazione fino all\'immensità di una cattedrale, applichiamo un riverbero algoritmico di altissima qualità per cullare il tuo sono nel giusto ambiente.', 'img/prodotti/ChromaVerb.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Compressor', '2.00', 'Controllo totale della dinamica. Livelliamo i picchi e diamo \"corpo\" alla tua traccia (voce, basso o batteria) emulando circuiti storici (VCA, FET, Opto). Il risultato è un suono compatto, potente e presente che non scompare mai dietro gli altri strumenti', 'img/prodotti/Compressor.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('DeEsser II', '1.50', 'Il tocco essenziale per tracce vocali o podcast perfetti. Riduciamo in modo mirato e chirurgico le sibilanti fastidiose(\"s\" e \"z\" troppo taglienti al microfono) senza scurire il tono generale della voce, garantendo un ascolto morbido e professionale.', 'img/prodotti/DeEsser_II.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Delay Designer', '1.50', 'Echi ritmici e atmosfere ipnotiche. Creiamo ritardi su misura per te: dai classici \"slapback\" per dare un tocco vintage a chitarre e voci, fino a complessi pattern stereo perfetti per arricchire sintetizzatori e produzioni elettroniche.', 'img/prodotti/Delay_Designer.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Izotope Ozone 8 Equalizer', '2.00', 'Pulizia chirurgica e brillantezza pure. Utilizziamo questo equalizzatore di livello mastering per rimuovere frequenze fastidiose (fango e risonanze nasali) ed esaltare la chiarezza e l\'aria della tua traccia con una precisione digitale assoluta.', 'img/prodotti/Izotope_Ozone_8_Equalizer.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Pedalboard', '2.00', 'Una pedaliera di effetti boutique a tua totale disposizione. Aggiungiamo un carattere alla tua traccia concatenando fuzz, overdrive, chorus, phaser o octaver. Ideale non solo per chitarre, ma anche per stravolgere in modo creativo synth o voci.', 'img/prodotti/Pedalboard.png');
INSERT INTO `saendwave`.`prodotto` (`nome`, `prezzo`, `descrizione`, `immagine`) VALUES ('Pitch Correction', '3.50', 'Intonazione perfetta e professionale per la tua traccia vocale. Che tu voglia una correzione invisibile e naturale, oppure l\'inconfondibile effetto \"robotico\" moderno (stile trap/pop), allineeremo le tue note all\'armonia del brano senza rovinare la tua espressività.', 'img/prodotti/Pitch_Correction.png');
INSERT INTO `saendwave`.`prodotto` (`ID_prodotto`, `nome`, `prezzo`, `descrizione`, `immagine`, `demo_dry`, `demo_wet`) VALUES ('12', 'Vocal Bundle', '8', 'Gestione tracce vocali per pulire ed enfatizzare , correggendo anche eventuali sbavature tramite Equalizzatore Izotope, Compressor, DeEsser e Pitch Correction.', '\'img/prodotti/1785338303882_vocal_bundle.jpeg', 'uploads/demoProdotti/dry_1785338303894_Audio_1SOF_NO_FX.wav', 'uploads/demoProdotti/wet_1785338303926_Audio_1SOF_FXgiusta.wav');
INSERT INTO `saendwave`.`prodotto` (`ID_prodotto`, `nome`, `prezzo`, `descrizione`, `immagine`, `demo_dry`, `demo_wet`) VALUES ('13', 'Chitarra Delay ', '7', 'Gestione tracce Chitarra per dare un effetto con Delay  per avere un suono arioso tramite Amp Designer, Equalizzatore Izotope, Compressor e Delay Designer.', 'img/prodotti/1785339029797_chitarrabundle.jpeg', 'uploads/demoProdotti/dry_1785339029801_Audio_1Vicarious_NO_FX.wav', 'uploads/demoProdotti/wet_1785339029811_Audio_1Vicarious_FX.wav');
INSERT INTO `saendwave`.`prodotto` (`ID_prodotto`, `nome`, `prezzo`, `descrizione`, `immagine`, `demo_dry`, `demo_wet`) VALUES ('14', 'Piano Bundle', '4.5', '\'Gestione tracce Pianoforte tramite Equalizzatore Izotope, Compressor e ChromaVerb', 'img/prodotti/1785339588389_pianobundle.jpeg', 'uploads/demoProdotti/dry_1785339588404_DonneRicche_no_FX.wav', 'uploads/demoProdotti/wet_1785339588442_DonneRicche_FX.wav\'');
INSERT INTO `saendwave`.`prodotto` (`ID_prodotto`, `nome`, `prezzo`, `descrizione`, `immagine`, `demo_dry`, `demo_wet`) VALUES ('15', 'Bass Distortion Bundle', '9', 'Gestione tracce Basso per suono distorto e potente tramite Bass Amp Designer, Equalizzatore Izotope, Compressor, Au Distortion e PedalBoard', 'img/prodotti/1785339759696_bassdistbundle.jpeg', 'uploads/demoProdotti/dry_1785339759697_Hysteria_NO_FX.wav', 'uploads/demoProdotti/wet_1785339759712_Hysteria_FX.wav');


INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('amplificatore', '1', '0');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('distorsore', '0', '1');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('riverbero', '1', '1');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('compressore', '1', '1');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('filtro', '1', '0');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('delay', '1', '1');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('equalizzatore', '1', '1');
INSERT INTO `saendwave`.`categoria` (`nome`, `studio_tool`, `effetto`) VALUES ('pedaliera', '0', '1');


INSERT INTO `tipologia` VALUES (1,'amplificatore'),(3,'amplificatore'),(5,'compressore'),(7,'delay'),(9,'delay'),(1,'distorsore'),(2,'distorsore'),(3,'distorsore'),(9,'distorsore'),(1,'equalizzatore'),(3,'equalizzatore'),(8,'equalizzatore'),(9,'equalizzatore'),(6,'filtro'),(9,'filtro'),(10,'filtro'),(9,'pedaliera'),(4,'riverbero'),(9,'riverbero');

INSERT INTO `contenuto` VALUES (7,10,4,3),(8,10,5,2),(9,10,8,1),(10,11,7,1),(11,11,9,2);

INSERT INTO `metodopagamento` VALUES (123,5333111111111111,'MARIO','ROSSI','12/30');

INSERT INTO `ordine` VALUES (10,'2026-07-20',5.5,'Completato','Eq spazio voce pulizia, comp rotonditÃ  e potenza, verb per spazialitÃ ',7,5333111111111111,'g.professionista@saendwave.it','master_ordine_10.wav'),(11,'2026-07-29',3.5,'In lavorazione','Nessuna istruzione particolare.',8,5333111111111111,NULL,NULL);

INSERT INTO `recensione` VALUES (1,NULL,7,'m.rossi@gmail.com','prodotto',4,'Suono pulito e ben cadenzato in base alle ottave scelte!','2026-07-27'),(2,NULL,4,'m.rossi@gmail.com','prodotto',5,'Ottima spazializzazione, suono intenso e caldo','2026-07-28'),(3,NULL,5,'m.rossi@gmail.com','prodotto',5,'Profondo e potente!','2026-07-28'),(4,NULL,8,'m.rossi@gmail.com','prodotto',4,'Pulizia eccellente e ottimo risultato sulle armoniche','2026-07-28'),(5,10,NULL,'m.rossi@gmail.com','ordine',5,'Ottimo lavoro','2026-07-28');

INSERT INTO `tracciaaudio` VALUES (7,'Baby_noFX.wav','1784194365841_Baby_noFX.wav','m.rossi@gmail.com'),(8,'Audio 1Vicarious_NO_FX.wav','1785320238306_Audio 1 Vicarious_NO_FX.wav','m.rossi@gmail.com');

INSERT INTO `utente` VALUES ('Admin','Gianni','adminGianni@saendwave.it','hPC6XUfMJVf9I3vsd/2YFGWoNGmheHDDrrioKaRIN2s=','1997-06-11','admin'),('Admin','Mary','adminMary@saendwave.it','KesYRkNecN4kTMEMbCKRg0B49GW16DRsSw5iFxIQYcc=','2006-03-07','admin'),('Giovanni','Pro','g.professionista@saendwave.it','Dm3AOGalRYVBDqeaiwb9NvrQp41ILh8Pf08BKmetxF4=','1997-06-11','professionista'),('Mario','Rossi','m.rossi@gmail.com','tbMBeUL7idLBIU7D8zdm9mlS23xUBbjlmsCW0/GNz/I=','1999-08-21','utente registrato'),('Professionista','Mary','professionistaMary@saendwave.it','KesYRkNecN4kTMEMbCKRg0B49GW16DRsSw5iFxIQYcc=','2006-03-07','professionista');

INSERT INTO `utilizzo` VALUES ('m.rossi@gmail.com',5333111111111111);